name: Build Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps: 
      - name: install go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.15.x
      - uses: actions/checkout@v2
      - name: test
        run: go build src/katanabroadcast.go
